[SETTING]
  LOG_FILE = "../log.log"
  EXAMPLE_PIC_DIR = "./ExamplePics"
  EXAMPLE_TXT_DIR = "./ExampleTxts"
  NAME=["系統資訊", "複製文", "圖片", "動圖", "影片"]
  BOT_TALK_THRESHOLD = 0.6
  
  [SETTING.TYPE]
    TXT=1
    IMG=2
    ANI=3
    VID=4
    

[API]
  [API.DC]
    TOKEN = "" # should be stored as environment variable
  [API.HF]
    TOKENs = [""] # should be stored as environment variable
    SUM_MODEL = "csebuetnlp/mT5_multilingual_XLSum"
    MT_MODEL = "Helsinki-NLP/opus-mt-en-zh" # not used, using google translation atm
  [API.MONGO]
    URI = ""# should be stored as environment variable
[DB]
  DB_NAME = "" # should be stored as environment variable
  GLOBAL_DB_NAME = "" # should be stored as environment variable
  CFormat = "%d-Copypasta" # args = ChatID int64
  
  GLOBAL_COL = "0_GLOBAL-Copypasta"
  CHAT_STATUS = "0_ChatStatus"
  USER_STATUS = "0_UserStatus"
