[SETTING]
  LOG_FILE = "./log.log"
  EXAMPLE_PIC_DIR = "./ExamplePics"
  EXAMPLE_TXT_DIR = "./ExampleTxts"
  NAME=["系統資訊", "複製文", "圖片", "動圖", "影片"]
  BOT_TALK_THRESHOLD = 0.6

  [SETTING.TYPE]
    TXT=1
    IMG=2
    ANI=3
    VID=4

# This bot supports dot-env files
[API]
  [API.DC]
    TOKEN = "" # is suggested to be stored as environment variable
  [API.HF]
    TOKENs = [""] # is suggested to be stored as environment variable, format is "TOKEN1 TOKEN2" (seperated with a single space)
    SUM_MODEL = "csebuetnlp/mT5_multilingual_XLSum"
    MT_MODEL = "Helsinki-NLP/opus-mt-en-zh" # currently not used, using google translation atm
  [API.MONGO]
    URI = ""# is suggested to be stored as environment variable
[DB]
  DB_NAME = "" # is suggested to be stored as environment variable
  GLOBAL_DB_NAME = "" # is suggested to be stored as environment variable
  CFormat = "%d-Copypasta" # args = ChatID int64

  GLOBAL_COL = "0_GLOBAL-Copypasta"
  CHAT_STATUS = "0_ChatStatus"
  USER_STATUS = "0_UserStatus"
